version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: system-database
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_NAME}
        volumes:
            - mongo.data:/data/db
        ports:
            - 127.0.0.1:${MONGO_PORT}:27018
        networks:
            - global
            
    image-marker:
        image: image-marker-img
        ports:
            - 8081:8081
    system-storage:
        image: system-storage-img
        ports:
            - 8082:8082
volumes:
    mongo.data:

networks:
    global:
        external: false

