version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: system-database
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_NAME}
        volumes:
            - mongo.data:/data/db
        ports:
            - 127.0.0.1:${MONGO_PORT}:27017
        networks:
            - global
            
    image-marker:
        image: image-marker-img
        container_name: image-marker
        ports:
            - 8081:8081
        networks:
            - global
            - image-marking-network
        volumes:
            - image-data:/data
        environment:
            - SYSTEM_STORAGE_USER_ENDPOINT=http://system-storage:8082/user
            - SYSTEM_STORAGE_LOGIN_ENDPOINT=http://system-storage:8082/login
            - SYSTEM_STORAGE_IMAGE_ENDPOINT=http://system-storage:8082/image
            - SYSTEM_STORAGE_LOGIN=${SYSTEM_STORAGE_LOGIN}
            - SYSTEM_STORAGE_PASSWORD=${SYSTEM_STORAGE_PASSWORD}
            
    system-storage:
        image: system-storage-img
        container_name: system-storage
        ports:
            - 8082:8082
        networks:
            - global
            - image-marking-network
        environment:
            - SYSTEM_STORAGE_LOGIN=${SYSTEM_STORAGE_LOGIN}
            - SYSTEM_STORAGE_PASSWORD=${SYSTEM_STORAGE_PASSWORD}
    
    user-register:
        image: user-register-img
        container_name: user-register
        ports:
            - 8083:8083
        networks:
            - global
            - image-marking-network
        environment:
            - SYSTEM_STORAGE_USER_ENDPOINT=http://system-storage:8082/user
            - SYSTEM_STORAGE_LOGIN_ENDPOINT=http://system-storage:8082/login
            - SYSTEM_STORAGE_LOGIN=${SYSTEM_STORAGE_LOGIN}
            - SYSTEM_STORAGE_PASSWORD=${SYSTEM_STORAGE_PASSWORD}
     
    system-client:
        image: system-client-img
        container_name: system-client
        ports:
            - 80:80
        networks:
            - global
            - image-marking-network
volumes:
    mongo.data:
    image-data:

networks:
    image-marking-network:
    global:
        external: false

