version: '2.1'

# Services we are going to use when running
services:
  # Database instance we need to store data
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=image-markerdb
      - MYSQL_USER=image-markeruser
      - MYSQL_PASSWORD=image-markerpassword
    # Internal port 3306 should always match mariaDB working port
    ports:
      - "3308:3306"

  # Backend instance that depends on database instance to start.
  backend:
    image: image-marker:latest
    mem_limit: 300m
    depends_on:
      - db
    environment:
      - ENVIRONMENT=dev
    restart: always
    # Internal port 3500 should always match your backend defined port
    ports:
      - "3510:3500"