OPTIONS http://127.0.0.1:8082/user
Accept: application/json

###
POST http://127.0.0.1:8082/user
Content-Type: application/json

{
  "name": "Dominik",
  "login": "test1",
  "password": "test1",
  "code": "ytest1"
}

###
GET http://127.0.0.1:8082/user/1
Accept: application/json