POST http://127.0.0.1:8082/user
Content-Type: application/json

{
  "name": "UserName",
  "login": "UserLogin",
  "password": "UserPassword",
  "code": "UserCode"
}

###
GET http://127.0.0.1:8082/user/UserLogin
Accept: application/json